### ISSUE TITLE
Can not run vscode when run test command

### ISSUE THREAD

**Issue by qiu8310** [microsoft/vscode-test#106] opened 2021-10-31 05:07 UTC
>
> Downloading VS Code 1.61.2 from https://update.code.visualstudio.com/1.61.2/darwin/stable: complete
> Downloaded VS Code 1.61.2 into /Users/Mora/Workspace/__test/prettier-vscode/.vscode-test/vscode-darwin-1.61.2
> Test error: Error: spawn /Users/Mora/Workspace/__test/prettier-vscode/.vscode-test/vscode-darwin-1.61.2/Visual Studio Code.app/Contents/MacOS/Electron EACCES
> Exit code:   -13
> Done
>

Step to reproduction:
1. git clone https://github.com/prettier/prettier-vscode.git
2. cd prettier-vscode
3. npm i
4. npm run test

NOTE: it will throw the same error in any vscode extension development environment, so I think this is something wrong in my own computer.

My computer environment:
macOS 10.15.7
node: v12.22.1

**Comment by qiu8310** [comment] 2021-10-31 08:32
The target file information（which has no execute permission):

> -rw-r--r--  1 Mora  staff  387824 10 20 00:28 /Users/Mora/Workspace/__test/prettier-vscode/.vscode-test/vscode-darwin-1.61.2/Visual Studio Code.app/Contents/MacOS/Electron

**Comment by connor4312** [comment] 2021-11-01 16:35
Hm, this works for me on macOS Big Sur (macOS 11), as well as lots . Maybe this is only an issue with older macOS versions or your setup?

**Comment by peakchen90** [comment] 2021-11-24 12:55
Same problem, macos 11.6

**Comment by connor4312** [comment] 2021-11-24 17:43
I cannot reproduce this

**Comment by and80506** [comment] 2021-12-20 06:27
+1, macOS Big Sur version 11.4

**Comment by chengcyber** [comment] 2022-01-16 14:54
+1 macOS 12.0.1, nodejs v14.15.4.

After manully run `sudo chmod +x /path/to/MacOS/Electron`, and then `runTest` throws

```
$ node ./out/test/runTest.js
Found /Users/admin/workspace/rushstack3/apps/vscode-extension/.vscode-test/vscode-darwin-1.63.2. Skipping download.
dyld[71236]: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/admin/workspace/rushstack3/apps/vscode-extension/.vscode-test/vscode-darwin-1.63.2/Visual Studio Code.app/Contents/MacOS/Electron
  Reason: tried: '/Users/admin/workspace/rushstack3/apps/vscode-extension/.vscode-test/vscode-darwin-1.63.2/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework' (not a mach-o file), '/Users/admin/workspace/rushstack3/apps/vscode-extension/.vscode-test/vscode-darwin-1.63.2/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework' (not a mach-o file), '/System/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file)

Exit code:   SIGABRT
```

**Comment by tjx666** [comment] 2022-02-02 13:11
same problem macos 12.2

vscode: 1.64.0-insider
@vscode/test-electron: 2.1.1

repo: https://github.com/tjx666/open-in-external-app

**Comment by qiu8310** [comment] 2022-02-03 07:39
> Hm, this works for me on macOS Big Sur (macOS 11), and we haven't gotten other reports of this. Maybe this is only an issue with older macOS versions or something else with your setup?

I think I found the problem: in my computer the download link is `https://update.code.visualstudio.com/1.63.2/darwin/stable` which is a `zip` file, but [in your code, take it as a `tgz` file](https://github.com/microsoft/vscode-test/blob/main/lib/download.ts#L101), so the extract method is wrong.

**Comment by connor4312** [comment] 2022-02-04 17:45
Fixed in https://github.com/microsoft/vscode-test/pull/125. Thanks @qiu8310!

**Closed by connor4312** 2022-02-04 17:45 UTC
