### ISSUE TITLE
Extract to tmp folder to avoid Windows unzip failure due to long path

### ISSUE THREAD

**Issue by NTaylorMullen** [microsoft/vscode-test#43] opened 2019-09-20 21:19 UTC
It says that the download was successful but the actual folder location (`.vscode-test`) is empty. I swear I had it work once but every time since it's failed.

![image](https://user-images.githubusercontent.com/2008729/65359258-d8d3d880-dbb0-11e9-9641-6177769076f6.png)

Here's the runTest.ts: https://github.com/aspnet/AspNetCore-Tooling/blob/53abe7754a09ac4caff4aff3ec91ee2de765a5a9/src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/runTest.ts

**Comment by octref** [comment] 2019-09-21 06:20
Does this only happen for insiders or stable as well? I suspect this is caused by #36.
When you run this locally on Windows, what's there in the `.vscode-test/vscode-insiders` folder?

The logic is here: https://github.com/microsoft/vscode-test/blob/master/lib/download.ts#L146-L163

**Comment by NTaylorMullen** [comment] 2019-09-23 17:30
Looks like it happens for non-insiders as well:

![image](https://user-images.githubusercontent.com/2008729/65448182-1329b980-dded-11e9-92b8-e1a040d5ea66.png)

![image](https://user-images.githubusercontent.com/2008729/65448208-25a3f300-dded-11e9-8f21-c177979ba7f1.png)

**Comment by octref** [comment] 2019-09-24 22:21
When you run the command, do you see something like this?

![image](https://user-images.githubusercontent.com/4033249/65554553-c6261000-dede-11e9-843e-932b1d859354.png)

We use `Expand-Archive` to expand the zip. What happens if you download the archive zip and try to unzip it?

- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-6
- https://github.com/microsoft/vscode-test/blob/master/lib/download.ts#L101

**Comment by NTaylorMullen** [comment] 2019-09-24 23:35
So it does that, however it stops half way through. So I did what you guys do manually:

1. Downloaded https://update.code.visualstudio.com/latest/win32-archive/insider
2. Put it in `.vscode-test` folder
3. Ran `Expand-Archive .\.vscode-test\VSCode-win32-ia32-1.39.0-insider.zip`
4. It barfed with a boatload of errors (lots more than shown in screenshot):
![image](https://user-images.githubusercontent.com/2008729/65557530-9aa82300-dee8-11e9-9cee-cf29ded1e005.png)

My bet is that it's one of the following:
1. You're running into long-path issues because you guys are trying to expand an archive in the projects relative path (instead of downloading the VSCode bits to a short-pathed temp folder). This is the mostly likely circumstance because trying to extract the folder manually with Windows Extract All results in:
![image](https://user-images.githubusercontent.com/2008729/65557679-05595e80-dee9-11e9-88d2-2943df013363.png)

2. Or the VSCode zip doesn't behave well with `Expand-Archive`. In .NET we've seen this in several circumstances where different flavors of .zip can occasionally barf on unzipping via different tools. This could be easily verified if this is the case by putting the VSCode zip in C:/ and trying to Extract All, I just didn't do that 😄

**Comment by octref** [comment] 2019-09-25 19:05
Opened https://github.com/microsoft/vscode/issues/81436

**Comment by octref** [comment] 2019-09-25 19:06
OTOH I can try to do the extraction on tmp folder and move the output.

**Comment by anurbol** [comment] 2019-10-25 08:53
Tried to run same steps as [here](https://github.com/microsoft/vscode-test/issues/43#issuecomment-534788146)
and got this:

![image](https://user-images.githubusercontent.com/3603448/67557638-425a8000-f737-11e9-9f6d-211921763077.png)

**Comment by octref** [comment] 2019-10-31 21:22
@anurbol You need at least Powershell 5.0 for this, as mentioned in README

**Comment by ajaybhargavb** [comment] 2019-12-18 22:05
Bump. This is preventing us from setting up the CI to run our tests.

**Comment by connor4312** [comment] 2021-01-16 01:33
Fixed in https://github.com/microsoft/vscode-test/commit/a20b727c52769b0a5c2a24de9ffa00515bd8e3b4 -- avoiding `Expand-Archive` seems to get around the issue.

**Closed by connor4312** 2021-01-16 01:33 UTC
Labels: feature-request
