### ISSUE TITLE
Can't activate extension on Github virtual enviornment

### ISSUE THREAD

**Issue by nigma456** [microsoft/vscode-test#96] opened 2021-04-12 03:28 UTC
We don't see the extension is activated on the Github virtual environment when running the mocha test.
For local machine test we can see the prompt when running NPM test:
extension is now active!
But for the Github virtual environment we don't see this and some of the unit test will fail.

**Comment by connor4312** [comment] 2021-04-12 04:35
Please provide a reproducable example of your issue.

**Comment by nigma456** [comment] 2021-04-12 06:05
May I know what the runTests() below does with the extension?	I can see it will download the vscode but I am not sure if it will also launch and activate the extesion as well during the mocha test?
await runTests({ extensionDevelopmentPath, extensionTestsPath });

An exmaple vscode extension :
https://github.com/Autodesk-AutoCAD/AutoLispExt

**Comment by connor4312** [comment] 2021-04-12 16:39
It opens VS Code in a way that it can load your extension from the path. It is still subject to the usual activationEvents

**Comment by nigma456** [comment] 2021-04-13 01:51
Does it activate the extension when doing the mocha test under the vscode-test framework?

**Comment by connor4312** [comment] 2021-04-13 02:54
> And if so how to make sure the extension is activated before the test running?

It doesn't -- the extension is still subject to the normal activation evetns

**Comment by nigma456** [comment] 2021-04-13 03:24
> It doesn't -- the extension is still subject to the normal activation evetns
But from my observation the extension is enabled on our local machine testing. Don't know why it behaviors differently on local and Github virtual machine?

**Comment by connor4312** [comment] 2021-04-13 03:53
Not with the information provided so far -- please provide a reproducable example 🙂

**Comment by nigma456** [comment] 2021-04-14 02:46
Here is our extension https://github.com/Autodesk-AutoCAD/AutoLispExt/pull/118
We have a setting for the extension defined in fmtconfig.ts and in out test cases we want to modify these setting as below:
let configuration = vscode.workspace.getConfiguration('autolispext');
vscode.workspace.getConfiguration('autolispext').update('format.LongListFormatStyle','Single Column');

But since the extension is not actually activate on the Github environment it will give the error message :
Error: Unable to write to User Settings because format.CloseParenthesisStyle is not a registered configuration.
https://github.com/Autodesk-AutoCAD/AutoLispExt/runs/2303324912?check_suite_focus=true#step:7:40

**Comment by connor4312** [comment] 2021-04-19 22:54
Ok, thanks for the details! Extension activation shouldn't have any relation to configuration; the configuration is in the package.json and is read without activation.

The extension [defines `autolispext.format.CloseParenthesisStyle`](https://github.com/Autodesk-AutoCAD/AutoLispExt/blob/13574b27b76fe521a3e5c7914f16c9a1d9978eac/package.json#L192), but in commit on that build it [looks like](https://github.com/Autodesk-AutoCAD/AutoLispExt/blob/29e224b7c8a7e186cb6c0fa38db842adcdb648b5/extension/src/test/suite/Formatter.test.ts#L18-L22) you're trying to update `format.CloseParenthesisStyle`, which would result in the error you see.

Let me know if you have other questions

**Comment by nigma456** [comment] 2021-05-06 01:33
I have ever tried this before and still can't resolve the problem.

https://github.com/Autodesk-AutoCAD/AutoLispExt/pull/141/files#diff-6a6799c9dce9f6030564ad09e96b7c7d9f0d20af94542380974796b2676cb744R17

**Comment by connor4312** [comment] 2021-05-06 03:12
It looks like the [extensionDevelopmentPath](https://github.com/Autodesk-AutoCAD/AutoLispExt/blob/736e29882fd7d4deced80aad675319954291b41e/extension/src/test/runTest.ts#L9) is not correct.

This does not seem to be an issue with the vscode-test module, thus closing the issue.

**Closed by connor4312** 2021-05-06 03:12 UTC
Labels: needs more info

**Comment by nigma456** [comment] 2021-05-07 01:21
Thank you for the help! Understand how the vscode-test and getConfiguration work now.
I have thought the getConfiguration read the setting from the vscode installation folder.
